/**
 * Browser-independent, English-only UI copy. Keep all shipped interface text here
 * so SSR and hydration always render the same labels.
 */
export const UI_COPY = {
  navigation: {
    mainMenu: "MAIN MENU",
    back: "BACK",
    menu: "MENU",
    openSettings: "OPEN SETTINGS",
    configure: "CONFIGURE",
    openEditor: "OPEN EDITOR",
    start: "START",
    settings: "SETTINGS",
  },
  menu: {
    titleLead: "Choose how to",
    titleAccent: "watch the race.",
    simulator: "AI FORMULA SPECTATOR SIMULATOR",
    chooseRace: "Choose how to\nwatch the race.",
    chooseRaceDescription: "Build your own circuits from connected track chunks, then watch fully AI-controlled drivers race them.",
    quickEvent: "QUICK EVENT",
    singleRace: "Single Race",
    singleRaceDescription: "Choose one of your saved circuits or let the game pick one.",
    system: "SYSTEM",
    settings: "Settings",
    settingsDescription: "Adjust the race, audio, and creation tools.",
    season: "SEASON",
    championship: "Championship",
    championshipDescription: "Set the number of rounds and compete on unique circuits.",
    circuits: "CIRCUITS",
    aiDrivers: "AI DRIVERS",
    fixedCamera: "FIXED CAMERA",
  },
  settings: {
    kicker: "SYSTEM CONFIGURATION",
    title: "GridWatch settings.",
    description: "Customize the race experience and access the available creation tools.",
    titleLead: "GridWatch",
    titleAccent: "settings.",
    raceControl: "RACE CONTROL",
    raceSettings: "Race Settings",
    raceDescription: "Set laps and grid size for the next events.",
    soundSystem: "SOUND SYSTEM",
    audio: "Audio",
    audioDescription: "Enable or disable the engines, effects, and race ambience.",
    appearance: "APPEARANCE",
    theme: "Theme",
    themeDescription: "Switch between the dark race-control palette and a lighter interface.",
    circuitEditor: "Circuit Editor",
    circuitEditorDescription: "Assemble SVG track chunks, connect routes, define racing lines, and place race facilities.",
    competitionEditor: "Competition Editor",
    competitionEditorDescription: "Create categories, teams, drivers, attributes, and sprites.",
    trackCreationTool: "TRACK CREATION TOOL",
    competitionCreationTool: "COMPETITION CREATION TOOL",
    raceTitle: { lead: "Race", accent: "settings." },
    appearanceTitle: { lead: "Choose the", accent: "theme." },
    audioTitle: { lead: "Control the", accent: "audio." },
    raceDefaultsDescription: "These values will be used as defaults in the Single Race and Championship menus.",
    appearanceFullDescription: "Choose the visual palette used across menus, editors, race controls, and results.",
    audioFullDescription: "Enable or disable the procedural soundtrack, engines, and race effects.",
    raceShort: "RACE",
    themeShort: "THEME",
    audioShort: "AUDIO",
    defaultLaps: "DEFAULT LAPS",
    defaultGrid: "DEFAULT GRID",
    colorTheme: "Color theme",
    dark: "DARK",
    darkDescription: "Race control",
    light: "LIGHT",
    lightDescription: "High clarity",
    audioStatus: "AUDIO STATUS",
    enabled: "ENABLED",
    disabled: "DISABLED",
    enableAudio: "ENABLE AUDIO",
    disableAudio: "DISABLE AUDIO",
  },
  setup: {
    requiredCategory: "CATEGORY · REQUIRED",
    selectCategory: "Select a category",
    official: "OFFICIAL",
    custom: "CUSTOM",
    carCount: (count: number) => `${count} ${count === 1 ? "car" : "cars"}`,
    randomCircuit: "Random · Pick a circuit",
    selectCategoryPrompt: "SELECT A CATEGORY",
    categoryDrivers: (count: number) => `${count} DRIVERS`,
    circuit: "CIRCUIT",
    laps: "LAPS",
    grid: "GRID",
    back: "BACK",
    confirmRace: "CONFIRM RACE",
    singleRace: "SINGLE RACE",
    championship: "CHAMPIONSHIP",
    singleTitle: "Build the next Grand Prix.",
    singleTitleLead: "Build the next",
    singleTitleAccent: "Grand Prix.",
    singleDescription: "Select one of your saved circuits. The Random option picks a different track when confirmed.",
    randomSelection: "RANDOM SELECTION",
    randomReveal: "The track will be revealed when confirmed",
    championshipTitle: "Create a season without repeats.",
    championshipTitleLead: "Create a season",
    championshipTitleAccent: "without repeats.",
    championshipDescription: "The calendar will be drawn before the first round. No circuit repeats in the same championship.",
    raceCount: "RACE COUNT · 2 TO 50",
    lapsPerRound: "LAPS PER ROUND",
    points: "POINTS",
    uniqueRounds: "UNIQUE ROUNDS",
    pointsScale: "25 · 18 · 15 · 12 · 10 · 8 · 6 · 4 · 2 · 1",
    categorySummary: (name: string, count: number) => `${name} · ${count} DRIVERS`,
    catalogPosition: (position: number, total: number) => `${String(position).padStart(2, "0")} / ${total}`,
    circuitLayout: (name: string) => `${name} circuit layout`,
    layoutStyle: (style: string) => `${style.toUpperCase()} LAYOUT`,
  },
  race: {
    start: "START RACE",
    pause: "PAUSE",
    resume: "RESUME",
    restart: "RESTART",
    nextRace: "NEXT RACE",
    results: "RESULTS",
    race: "RACE",
    setup: "SETUP",
    simulation: "SIMULATION",
    actions: "Race actions",
    laps: "LAPS",
    grid: "GRID",
    leaderboard: "Race leaderboard",
    audioOn: "Enable race audio",
    audioOff: "Mute race audio",
    loadingPhysics: "LOADING PHYSICS",
    physicsFallback: "PHYSICS FALLBACK",
    status: {
      ready: "READY",
      countdown: "STARTING",
      racing: "LIVE",
      paused: "PAUSED",
      finished: "FINISHED",
    },
    openActions: "Open race actions",
    lapsLabel: "Race laps",
    gridLabel: "Race grid size",
    simulationSpeed: "Simulation speed",
    volumeOn: "VOLUME ON",
    mute: "MUTE",
    volumeShort: "VOL",
    liveTiming: "LIVE TIMING",
    raceOrder: "Race order",
    position: "POS",
    car: "CAR",
    driver: "DRIVER",
    gap: "GAP",
    teamColor: "Team color",
    lap: "LAP",
    raceTime: "RACE TIME",
    leader: "LEADER",
    bestLap: "BEST LAP",
  },
  championship: {
    viewStandings: "VIEW CHAMPIONSHIP STANDINGS",
    viewResults: "VIEW CHAMPIONSHIP RESULTS",
    playbackMode: "CHAMPIONSHIP PLAYBACK",
    manual: "MANUAL",
    manualDescription: "Continue between rounds",
    autoBroadcast: "AUTO BROADCAST",
    autoBroadcastDescription: "Watch the full season unattended",
    autoBroadcastActive: "AUTO BROADCAST ACTIVE",
    autoBroadcastPaused: "AUTO ADVANCE PAUSED",
    pauseBroadcast: "PAUSE AUTO ADVANCE",
    resumeBroadcast: "RESUME AUTO ADVANCE",
    skipPresentation: "SKIP PRESENTATION",
    nextRoundNow: "NEXT ROUND NOW",
    drawChampionship: "DRAW CHAMPIONSHIP",
    startAutoBroadcast: "START AUTO BROADCAST",
    standingsAutoAdvance: "The next round starts automatically after this presentation.",
    standingsManualAdvance: "The next round begins when you continue.",
    standingsAfterResult: "Championship standings are available after this official result.",
    standingsLabel: "Championship standings",
    partialStandingsLabel: "Partial championship standings",
    partialStandings: "Partial standings",
    currentStandings: "Current championship standings",
    pointsShort: "PTS",
    winsShort: "WINS",
    tiebreak: "TIEBREAK: POINTS, WINS, BEST RESULTS",
    roundLabel: (round: number) => `CHAMPIONSHIP · ROUND ${round}`,
    roundComplete: (round: number) => `ROUND ${round} COMPLETE`,
    roundsRemaining: (rounds: number) => `${rounds} ROUNDS REMAINING`,
    recoveryTitle: "CHAMPIONSHIP READY TO RESUME",
    recoveryDescription: (completed: number, total: number) => `${completed} of ${total} rounds are complete. Resume from the next round boundary or discard this saved season.`,
    resumeChampionship: "RESUME CHAMPIONSHIP",
    inspectStandings: "INSPECT STANDINGS",
    discardSession: "DISCARD SAVED SEASON",
    resultDuration: "RESULT SCREEN · SECONDS",
    standingsDuration: "STANDINGS SCREEN · SECONDS",
    pauseWhenHidden: "PAUSE WHEN TAB IS HIDDEN",
  },
  results: {
    raceResults: "Race results",
    officialRaceResult: "OFFICIAL RACE RESULT",
    raceComplete: "Race complete",
    finalClassification: "Final race classification",
    timeGap: "TIME / GAP",
    best: "BEST",
    finishGapNote: "Final gaps are measured at each car’s finish line crossing.",
    championshipComplete: "CHAMPIONSHIP COMPLETE",
    newChampionship: "NEW CHAMPIONSHIP",
    bestLapLabel: (time: string) => `BEST LAP ${time}`,
    championSummary: (points: number, rounds: number) => `${points} points · ${rounds} rounds`,
  },
  editor: {
    discardChanges: "Discard unsaved changes?",
    loadingLibrary: "LOADING LIBRARY",
    restoringCircuits: "Restoring your local circuits…",
    restoringCategories: "Restoring your local categories…",
    track: {
      creationTool: "TRACK CREATION TOOL",
      title: "CIRCUIT EDITOR",
      tools: "Editor tools",
      editingArea: "Circuit editing area",
      select: "Select",
      createPoint: "Create point",
      removePoint: "Remove point",
      smoothCurve: "Smooth curve",
      addElement: "Add element",
      finalMode: "Final mode · no editing controls",
      canvasHint: "Drag track chunks to adjust the layout · connect matching ports to build a closed route",
      fixGeometry: "Fix the geometry issues before saving.",
      storageFailure: "Could not save to browser storage.",
      saved: "Circuit saved locally.",
      addElementHint: (label: string) => `Click in the environment to add: ${label}.`,
      snap: "Snap chunks and racing-line points to a 10-meter grid",
      circuitMetrics: "CIRCUIT METRICS",
      length: "LENGTH",
      controlPoints: "TRACK CHUNKS",
      sharpestCorner: "SHARPEST CORNER",
      duplicatePoint: "DUPLICATE POINT",
      startPoint: "START / FINISH",
    },
    competition: {
      loading: "LOADING CATEGORIES",
      restoring: "Restoring your local library…",
      duplicated: "Category duplicated.",
      removed: "Category removed.",
      officialProtected: "Official categories cannot be removed. Duplicate them to edit.",
      protectedSave: "The official category is protected. Duplicate it to save a custom version.",
      fixIssues: "Fix the issues before saving.",
      storageFailure: "Could not save to browser storage.",
      saved: "Category saved.",
      jsonTooLarge: "The JSON file exceeds the 2 MB limit.",
      imported: "Category imported and normalized.",
      invalidJson: "Invalid or incompatible JSON file.",
      spriteTooLarge: "The sprite file exceeds the 10 MB limit.",
      invalidSprite: "Invalid sprite file.",
      importedSprite: (view: "main" | "lateral") => `Imported ${view === "main" ? "top" : "lateral"} sprite.`,
      spriteReadFailure: "Could not read the sprite file.",
      removeTeam: (name: string) => `Remove ${name}?`,
      removeTeamAndReassign: (name: string, count: number, fallback: string) => `Remove ${name} and reassign ${count} ${count === 1 ? "driver" : "drivers"} to ${fallback}?`,
      lastTeamProtected: "A category must retain at least one team.",
      driversReassigned: (count: number, team: string) => `${count} ${count === 1 ? "driver was" : "drivers were"} reassigned to ${team}.`,
      teamName: (name: string) => `Team name ${name}`,
      teamCode: (name: string) => `Team code ${name}`,
      blueColor: (name: string) => `Blue template color for ${name}`,
      greenColor: (name: string) => `Green template color for ${name}`,
      thirdColor: (name: string) => `White template color for ${name}`,
      removeTeamLabel: (name: string) => `Remove team ${name}`,
      vehiclePhysics: "VEHICLE PHYSICS",
      vehiclePhysicsDescription: "Physical category values used by the world-space racing engine.",
      mass: "MASS · KG",
      engineForce: "ENGINE FORCE · N",
      brakeForce: "BRAKE FORCE · N",
      tireGrip: "TIRE GRIP",
      downforce: "DOWNFORCE",
      steeringLock: "STEERING LOCK · DEG",
      moveUp: "Move up",
      moveDown: "Move down",
      duplicateDriver: "DUPLICATE DRIVER",
      recoverDraft: (name: string) => `Recover the autosaved draft for ${name}?`,
      draftRecovered: "Autosaved draft recovered.",
      draftAutosaved: "Draft autosaved locally.",
      spriteDimensionsInvalid: "Sprite dimensions must be between 16 and 4096 pixels per side.",
      spriteMaskReport: (missing: string[]) => missing.length ? `Sprite mask report: missing ${missing.join(", ")}.` : "Sprite mask report: Blue, Green, White, Red, and Yellow channels detected.",
      importPreview: "IMPORT PREVIEW",
      confirmImport: "IMPORT CATEGORY",
      cancelImport: "CANCEL",
    },
  },
} as const;
